### ISSUE TITLE
Impossible to start run

### ISSUE THREAD

**Issue by filippo-ciceri** [tsahota/NMproject#18]
I follow the same instructions as in the vignette however I cannot start a run.
I define a model with the code:

```
m1 <- new_nm(run_id="m1",
                         based_on = "staging/Models/ADVAN2.mod",
                         data_path = "DerivedData/data.csv") %>%
  cmd("execute {ctl_name} -dir={run_dir}") %>%
  fill_input() %>%
  init_theta(init = c(-2, 0.5, 1)) %>%
  init_sigma(init = c(0.1, 0.1)) %>%
  run_in("Models/demo") %>% 
  run_nm(force = TRUE)

```
However the status (```status(m1)```)  is "not_started".
Any template to visualize results get stuck on ```wait_finish(m1)``` eternally.

Do you have any idea for this behaviour?
Thanks

**Comment by tsahota** [comment]
Update: I can only reproduce the error in windows if PsN is not installed on the system.  If PsN has already been installed, I recommend reinstalling PsN.

**Comment by tsahota** [comment]
I've created another issue off this for version 0.6.7 to make the error more informative.  It'll fail with instructions and a link to install PsN.  Thanks for your feedback, Filippo!
